---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: mapping-stamp-chat-auth
spec:
  prefix: /auth/
  service: stamp-chat-auth.default:3000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: mapping-stamp-chat-channels
spec:
  prefix: /chat/
  service: stamp-chat-channels.default:4000
  allow_upgrade:
  - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: mapping-stamp-chat-notifications
spec:
  prefix: /notifications/
  service: stamp-chat-notifications.default:3001
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: internal-routes
spec:
  precedence: 1
  prefix: ".*/internal/.*"
  prefix_regex: true
  rewrite: "/404/"
  service: localhost:8500