apiVersion: apps/v1
kind: Deployment
metadata:
  name: stamp-chat-notifications
  labels:
    app: stamp-chat-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stamp-chat-notifications
  template:
    metadata:
      labels:
        app: stamp-chat-notifications
    spec:
      initContainers:
      - name: init-stamp-chat-notifications
        image: osamadev/stamp_chat_notifications:0.1.4
        env:
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notifications-stamp-chat-secret
              key: database_url
        command: ['sh', '-c', '/app/node_modules/.bin/knex migrate:latest']
      containers:
      - name: stamp-chat-notifications
        image: osamadev/stamp_chat_notifications:0.1.4
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notifications-stamp-chat-secret
              key: database_url
        - name: FIREBASE_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: firebase-secret
              key: firebase_service_account
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: auth-stamp-chat-secret
              key: private_key
---
apiVersion: v1
kind: Service
metadata:
  name: stamp-chat-notifications
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: stamp-chat-notifications