apiVersion: apps/v1
kind: Deployment
metadata:
  name: stamp-chat-channels
  labels:
    app: stamp-chat-channels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stamp-chat-channels
  template:
    metadata:
      labels:
        app: stamp-chat-channels
    spec:
      initContainers:
      - name: init-stamp-chat-channels
        image: osamadev/stamp_chat_channels:0.1.6
        env:
        - name: MIX_ENV
          value: "prod"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: channels-stamp-chat-secret
              key: database_url
        - name: PORT
          value: "4000"
        - name: SECRET_KEY_BASE
          value: abc123abc1232
        command: ['sh', '-c', '/home/app/prod/rel/chat/bin/chat eval "Chat.Release.migrate"']
      containers:
      - name: stamp-chat-channels
        image: osamadev/stamp_chat_channels:0.1.6
        ports:
        - containerPort: 4000
        env:
        - name: MIX_ENV
          value: "prod"
        - name: PORT
          value: "4000"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: channels-stamp-chat-secret
              key: secret_key_base
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: auth-stamp-chat-secret
              key: private_key
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: channels-stamp-chat-secret
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: stamp-chat-channels
spec:
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  selector:
    app: stamp-chat-channels